version: '3.8'

services:
  php:
    container_name: php
    build:
      context: .docker/php
    networks:
      - web-app-bridge
      - proxy
    volumes:
      - ./:/var/www/symfony_docker
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./.docker/php/conf.d/docker-php-config.ini:/usr/local/etc/php/conf.d/docker-php-config.ini
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    networks:
      - web-app-bridge
      - proxy
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    volumes:
      - ./:/var/www/symfony_docker
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app_symfony.rule=HostRegexp(`$NGINX_HOST`)"
      - "traefik.http.routers.app_symfony.entrypoints=websecure"
      - "traefik.http.routers.app_symfony.tls=true"
      - "traefik.http.routers.app_symfony.tls.certresolver=cloudflare"
      - "traefik.http.routers.app_symfony.tls.domains[0].main=$NGINX_HOST"

networks:
  web-app-bridge:
    driver: bridge
  proxy:
    external:
      name: "traefik_proxy"